language: c

before_install:
   - sudo apt-get update
   - sudo apt-get install gcc-multilib # needed for dmd on travis
   - make DC=$DC download
   - case "$DC" in
       dmd)
         ;;
       gdc)
         export PATH=$PATH:$PWD/x86_64-gdcproject-linux-gnu/bin;
         ;;
       ldc2)
         export PATH=$PATH:$PWD/ldc2-0.14.0-linux-x86_64/bin;
         ;;
     esac
   - make download_dub
   - export PATH=$PATH:$PWD/

env:
   global:
       - secure: "a5uPvUZg3AXRvKuPTh/6tbbjmWEuZJzY7jg18SyPUKVDve9kg1UNEzJuq86e7Oobo+adMFFeF2x9XihMzwa/USIjdbalqZJIi/A2Pe9zaU6f+3IKNjo92cZe2WLE4twIjwLhftN6ybowrg9wqsDp8Afy/Wcn23v1NpLX6qECT9o="
   matrix:
     - DC="dmd" BUILD="release"
     - DC="dmd" BUILD="debug"
     - DC="gdc" BUILD="release"
     - DC="gdc" BUILD="debug"
     - DC="ldc2" BUILD="release"
     - DC="ldc2" BUILD="debug"

script:
   - make DC=$DC BUILD=$BUILD
   - make DC=$DC BUILD=$BUILD tests
   - test ! $DC = "dmd" || make DC=$DC BUILD=$BUILD coverage

after_success:
   - dub fetch doveralls
   - test $TRAVIS_REPO_SLUG = "jkmfsu/lang" && dub run doveralls -- -p $PWD -t $COVERALLS_TOKEN
